# Generated by Django 5.0 on 2024-09-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='dm-media/'),
        ),
        migrations.RemoveField(
            model_name='profilemedia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pfp',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pfps/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='image',
            field=models.ImageField(upload_to='post-media/'),
        ),
        migrations.DeleteModel(
            name='ConvoMedia',
        ),
        migrations.DeleteModel(
            name='ProfileMedia',
        ),
    ]
