# Generated by Django 5.0 on 2024-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
