# Generated by Django 5.0 on 2024-09-29 14:39

from django.db import migrations
from django.contrib.auth import get_user_model
from api.models import Profile

def create_admin_user(apps, schema_editor):
    User = get_user_model()
    admin_email = 'admin@tolink.com'
    admin_password = 'adminpassword123'

    if not User.objects.filter(email=admin_email).exists():
        admin_user = User.objects.create_superuser(
            email=admin_email,
            password=admin_password,
            name='Admin',
            surname='User',
        )

        Profile.objects.create(
            user=admin_user,   # Link the profile 
            name="Mpampis",
            surname="Sougias",
            email=admin_user.email
            
        )



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
