# Generated by Django 5.0 on 2024-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apl_cnt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
