# Generated by Django 5.0 on 2024-08-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_cnt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='listings_cnt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_cnt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
