# Generated by Django 5.0 on 2024-09-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(db_column='Comment_ID', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(db_column='Post_ID', on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
    ]
