# Generated by Django 5.0 on 2024-09-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dm_media_remove_profilemedia_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='pfp',
        ),
    ]
