# Generated by Django 5.0 on 2024-09-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listing_apl_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvoMedia',
            fields=[
                ('convo_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='covomedia/')),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.convo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='dm',
            name='media',
            field=models.ForeignKey(blank=True, db_column='Media_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.convomedia'),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('post_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='postmedia/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('profile_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profilemedia/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
