# Generated by Django 5.0 on 2024-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_unique_together_comment_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
