# This is a test bench for the API functionality

### Login API 
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"email": "jim", "password": "James"}

### Sign Up API

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"name": "James", "surname": "James", "email": "jim", "password":"James", "country": "James", "city": "James", "phone": "123", "birthdate": "2003-12-02"}

### Profile Update API

PUT http://127.0.0.1:8000/profile/update/
Cookie: sessionid=it3wx3pr59jlig5a4rxtmb8knogkyioh; csrftoken=idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR;
X-CSRFToken: idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR
Content-Type: application/json

{
    "pfp": "BBB.jpg",
    "name": "Updated Name",
    "surname": "Updated Surname",
    "title": "Updated Title",
    "bio": "Updated Bio",
    "phone": "1234567890",
    "website": "http://newwebsite.com",
    "experience": {"company": "New Company", "position": "New Position"},
    "education": {"school": "New School", "degree": "New Degree"}
}

### Upload Post API

POST http://127.0.0.1:8000/posts/upload/
Content-Type: application/json
Cookie: sessionid=it3wx3pr59jlig5a4rxtmb8knogkyioh; csrftoken=idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR;
X-CSRFToken: idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR

{
  "text": "This is a sample post.",
  "media": {"images": ["image1.png", "image2.png"]},
  "links": {"link1": "http://example.com"}
}


### Fetch Post API

POST http://127.0.0.1:8000/posts/view/
Content-Type: application/json
Cookie: sessionid=it3wx3pr59jlig5a4rxtmb8knogkyioh; csrftoken=idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR;
X-CSRFToken: idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR

{
  "post_id": 2
}

### Like/Unlike Post API

POST http://127.0.0.1:8000/posts/like/
Content-Type: application/json
Cookie: sessionid=it3wx3pr59jlig5a4rxtmb8knogkyioh; csrftoken=idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR;
X-CSRFToken: idIIa9M8ynhW7FOwUNyVZzi5x25EVAvR

{
  "post_id": 1
}

### Comment Post API

POST http://127.0.0.1:8000/posts/comment/new
Content-Type: application/json
Cookie: sessionid=m4iv3sfxwobhd137n7f4dfw3ae167hsr; csrftoken=DoRC7DLel6KMcPCrRByh2xDMHUeMEKka;
X-CSRFToken: DoRC7DLel6KMcPCrRByh2xDMHUeMEKka

{
  "post": 1,
  "text": "No stop!"
}

### Fetch Comments API

POST http://127.0.0.1:8000/posts/comment/show
Content-Type: application/json
Cookie: sessionid=m4iv3sfxwobhd137n7f4dfw3ae167hsr; csrftoken=DoRC7DLel6KMcPCrRByh2xDMHUeMEKka;
X-CSRFToken: DoRC7DLel6KMcPCrRByh2xDMHUeMEKka

{
  "post": 1
}