# This is a test bench for the API functionality

### Login API 
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"email": "ji", "password": "James"}

### Sign Up API

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"name": "James", "surname": "James", "email": "ji", "password":"James", "country": "James", "city": "James", "phone": "123", "birthdate": "2003-12-02"}

### Profile Update API

PUT http://127.0.0.1:8000/profile/own/update/
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9
Content-Type: application/json

{
    "pfp": "BBB.jpg",
    "name": "Updated Name",
    "surname": "Updated Surname",
    "title": "Updated Title",
    "bio": "Updated Bio",
    "phone": "1234567890",
    "website": "http://newwebsite.com",
    "experience": {"company": "New Company", "position": "New Position"},
    "education": {"school": "New School", "degree": "New Degree"}
}

### Fetch your profile api

POST http://127.0.0.1:8000/profile/own/fetch
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
}

### Fetch outside profile

POST http://127.0.0.1:8000/profile/view/
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "user_id": 2
}


### Upload Post API

POST http://127.0.0.1:8000/posts/upload/
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "text": "This is a sample post.",
  "media": {"images": ["image1.png", "image2.png"]},
  "links": {"link1": "http://example.com"}
}


### Fetch Post API

POST http://127.0.0.1:8000/posts/view/
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "post_id": 2
}

### Like/Unlike Post API

POST http://127.0.0.1:8000/posts/like/
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "post_id": 2
}

### Comment Post API

POST http://127.0.0.1:8000/posts/comment/new
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "post": 2,
  "text": "No stop!"
}

### Fetch Comments API

POST http://127.0.0.1:8000/posts/comment/show
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "post": 2
}




###### Testing George ######
### Testing Requests
POST http://127.0.0.1:8000/request/new
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "request_id": 2
}


### Testing Requests
POST http://127.0.0.1:8000/request/respond
Content-Type: application/json
Cookie: sessionid=voxn1ekrdotdz1ksnuu88vq9zdgcf264; csrftoken=8A8wBzBfuuysMWdW3x4N85WllAXoglvJ;
X-CSRFToken: 8A8wBzBfuuysMWdW3x4N85WllAXoglvJ

{
  "request_id": 1,
  "request_response": "accept"
}


### Testing Requests
POST http://127.0.0.1:8000/links/list
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
}

### Testing Requests
POST http://127.0.0.1:8000/request/list
Content-Type: application/json
Cookie: sessionid=voxn1ekrdotdz1ksnuu88vq9zdgcf264; csrftoken=8A8wBzBfuuysMWdW3x4N85WllAXoglvJ;
X-CSRFToken: 8A8wBzBfuuysMWdW3x4N85WllAXoglvJ

{
}


### Convo and Messenging Testing

POST http://127.0.0.1:8000/convo/list/
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
}

###

POST http://127.0.0.1:8000/convo/dm/new
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "convo": "1",
  "text": "aaaa"
}

###

POST http://127.0.0.1:8000/convo/dm/fetch
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "convo": "1"
}

###

POST http://127.0.0.1:8000/convo/find/
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "other_user": "2"
}

###

POST http://127.0.0.1:8000/convo/list/
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
}

###

POST http://127.0.0.1:8000/listings/new
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "title": "Nothing Much",
  "visible": 3,
  "spot": "Hybrid",
  "time": "Full-time",
  "level": "Entry-level",
  "desc": "Kati poly symantiko"
}

###

POST http://127.0.0.1:8000/listings/list
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "specify_user": 2
}

###

POST http://127.0.0.1:8000/listings/fetch
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
}

###

POST http://127.0.0.1:8000/listings/applied/fetch
Content-Type: application/json
Cookie: sessionid=9b4jnvvzyiem8c8z0yah8g6fxllgetv1; csrftoken=HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9;
X-CSRFToken: HuFATLQXxbgzoERYUsfv4nnOx8xz4JX9

{
  "listing_id": 1
}

###

POST http://127.0.0.1:8000/listings/applied/new
Content-Type: application/json
Cookie: sessionid=voxn1ekrdotdz1ksnuu88vq9zdgcf264; csrftoken=8A8wBzBfuuysMWdW3x4N85WllAXoglvJ;
X-CSRFToken: 8A8wBzBfuuysMWdW3x4N85WllAXoglvJ

{
  "listing_id": 1
}



###

POST http://127.0.0.1:8000/admin/fetch/connections
Content-Type: application/json
Cookie: sessionid=voxn1ekrdotdz1ksnuu88vq9zdgcf264; csrftoken=8A8wBzBfuuysMWdW3x4N85WllAXoglvJ;
X-CSRFToken: 8A8wBzBfuuysMWdW3x4N85WllAXoglvJ

{
  "user_id": 2
}
